FROM python:3.7
ENV PYTHONUNBUFFERED 1
RUN apt-get update
RUN echo "Installing GDAL dependencies" && \
    apt-get install -y libgdal-dev libcurl4-gnutls-dev librtmp-dev && \
    echo "Installing other depdencies" && \
    apt-get install -y wait-for-it && \
    echo "Install C library for geoip2" && \
    apt install libmaxminddb0 libmaxminddb-dev mmdb-bin && \
    echo "Removing build dependencies and cleaning up" && \
    rm -rf /var/lib/apt/lists/* && \
    rm -rf ~/.cache/pip

RUN mkdir /code
WORKDIR /code

RUN apt-get update && apt-get install -y curl && curl -LJO https://github.com/P3TERX/GeoLite.mmdb/raw/download/GeoLite2-City.mmdb && \
    mkdir /var/opt/maxmind && \
    mv GeoLite2-City.mmdb /var/opt/maxmind/GeoLite2-City.mmdb
    
ENV GEOIP_PATH=/var/opt/maxmind/

COPY REQUIREMENTS.txt /code/
RUN pip install -r REQUIREMENTS.txt
COPY ./entrypoint_testing.sh /code/
