# coding=utf-8
""""Languages from ISO-939-1

.. note:: This program is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

"""

__author__ = 'elpaso@itopen.it'
__date__ = '2019-05-07'
__copyright__ = 'Copyright 2019, ItOpen'


LANGUAGES = (
  ("aa", "Afar"),
  ("ab", "Abkhazian"),
  ("ae", "Avestan"),
  ("af", "Afrikaans"),
  ("ak", "Akan"),
  ("am", "Amharic"),
  ("an", "Aragonese"),
  ("ar", "Arabic"),
  ("as", "Assamese"),
  ("av", "Avaric"),
  ("ay", "Aymara"),
  ("az", "Azerbaijani"),
  ("ba", "Bashkir"),
  ("be", "Belarusian"),
  ("bg", "Bulgarian"),
  ("bh", "Bihari languages"),
  ("bi", "Bislama"),
  ("bm", "Bambara"),
  ("bn", "Bengali"),
  ("bo", "Tibetan"),
  ("br", "Breton"),
  ("bs", "Bosnian"),
  ("ca", "Catalan; Valencian"),
  ("ce", "Chechen"),
  ("ch", "Chamorro"),
  ("co", "Corsican"),
  ("cr", "Cree"),
  ("cs", "Czech"),
  ("cu", "Church Slavic"),
  ("cv", "Chuvash"),
  ("cy", "Welsh"),
  ("da", "Danish"),
  ("de", "German"),
  ("dv", "Divehi; Dhivehi; Maldivian"),
  ("dz", "Dzongkha"),
  ("ee", "Ewe"),
  ("el", "Greek, Modern"),
  ("en", "English"),
  ("eo", "Esperanto"),
  ("es", "Spanish; Castilian"),
  ("et", "Estonian"),
  ("eu", "Basque"),
  ("fa", "Persian"),
  ("ff", "Fulah"),
  ("fi", "Finnish"),
  ("fj", "Fijian"),
  ("fo", "Faroese"),
  ("fr", "French"),
  ("fy", "Western Frisian"),
  ("ga", "Irish"),
  ("gd", "Gaelic; Scottish Gaelic"),
  ("gl", "Galician"),
  ("gn", "Guarani"),
  ("gu", "Gujarati"),
  ("gv", "Manx"),
  ("ha", "Hausa"),
  ("he", "Hebrew"),
  ("hi", "Hindi"),
  ("ho", "Hiri Motu"),
  ("hr", "Croatian"),
  ("ht", "Haitian; Haitian Creole"),
  ("hu", "Hungarian"),
  ("hy", "Armenian"),
  ("hz", "Herero"),
  ("ia", "Interlingua"),
  ("id", "Indonesian"),
  ("ie", "Interlingue; Occidental"),
  ("ig", "Igbo"),
  ("ii", "Sichuan Yi; Nuosu"),
  ("ik", "Inupiaq"),
  ("io", "Ido"),
  ("is", "Icelandic"),
  ("it", "Italian"),
  ("iu", "Inuktitut"),
  ("ja", "Japanese"),
  ("jv", "Javanese"),
  ("ka", "Georgian"),
  ("kg", "Kongo"),
  ("ki", "Kikuyu; Gikuyu"),
  ("kj", "Kuanyama; Kwanyama"),
  ("kk", "Kazakh"),
  ("kl", "Kalaallisut; Greenlandic"),
  ("km", "Central Khmer"),
  ("kn", "Kannada"),
  ("ko", "Korean"),
  ("kr", "Kanuri"),
  ("ks", "Kashmiri"),
  ("ku", "Kurdish"),
  ("kv", "Komi"),
  ("kw", "Cornish"),
  ("ky", "Kirghiz; Kyrgyz"),
  ("la", "Latin"),
  ("lb", "Luxembourgish; Letzeburgesch"),
  ("lg", "Ganda"),
  ("li", "Limburgan; Limburger; Limburgish"),
  ("ln", "Lingala"),
  ("lo", "Lao"),
  ("lt", "Lithuanian"),
  ("lu", "Luba-Katanga"),
  ("lv", "Latvian"),
  ("mh", "Marshallese"),
  ("ml", "Malayalam"),
  ("mr", "Marathi"),
  ("mk", "Macedonian"),
  ("mg", "Malagasy"),
  ("mt", "Maltese"),
  ("mn", "Mongolian"),
  ("mi", "Maori"),
  ("ms", "Malay (macrolanguage)"),
  ("my", "Burmese"),
  ("na", "Nauru"),
  ("nv", "Navajo"),
  ("nr", "South Ndebele"),
  ("nd", "North Ndebele"),
  ("ng", "Ndonga"),
  ("ne", "Nepali (macrolanguage)"),
  ("nl", "Dutch"),
  ("nn", "Norwegian Nynorsk"),
  ("nb", "Norwegian Bokmål"),
  ("no", "Norwegian"),
  ("ny", "Nyanja"),
  ("oc", "Occitan (post 1500)"),
  ("oj", "Ojibwa"),
  ("or", "Oriya (macrolanguage)"),
  ("om", "Oromo"),
  ("os", "Ossetian"),
  ("pa", "Panjabi"),
  ("pi", "Pali"),
  ("pl", "Polish"),
  ("pt", "Portuguese"),
  ("ps", "Pushto"),
  ("qu", "Quechua"),
  ("rm", "Romansh"),
  ("ro", "Romanian"),
  ("rn", "Rundi"),
  ("ru", "Russian"),
  ("sg", "Sango"),
  ("sa", "Sanskrit"),
  ("si", "Sinhala"),
  ("sk", "Slovak"),
  ("sl", "Slovenian"),
  ("se", "Northern Sami"),
  ("sm", "Samoan"),
  ("sn", "Shona"),
  ("sd", "Sindhi"),
  ("so", "Somali"),
  ("st", "Southern Sotho"),
  ("es", "Spanish"),
  ("sq", "Albanian"),
  ("sc", "Sardinian"),
  ("sr", "Serbian"),
  ("ss", "Swati"),
  ("su", "Sundanese"),
  ("sw", "Swahili (macrolanguage)"),
  ("sv", "Swedish"),
  ("ty", "Tahitian"),
  ("ta", "Tamil"),
  ("tt", "Tatar"),
  ("te", "Telugu"),
  ("tg", "Tajik"),
  ("tl", "Tagalog"),
  ("th", "Thai"),
  ("ti", "Tigrinya"),
  ("to", "Tonga (Tonga Islands)"),
  ("tn", "Tswana"),
  ("ts", "Tsonga"),
  ("tk", "Turkmen"),
  ("tr", "Turkish"),
  ("tw", "Twi"),
  ("ug", "Uighur"),
  ("uk", "Ukrainian"),
  ("ur", "Urdu"),
  ("uz", "Uzbek"),
  ("ve", "Venda"),
  ("vi", "Vietnamese"),
  ("vo", "Volapük"),
  ("wa", "Walloon"),
  ("wo", "Wolof"),
  ("xh", "Xhosa"),
  ("yi", "Yiddish"),
  ("yo", "Yoruba"),
  ("za", "Zhuang"),
  ("zh", "Chinese"),
  ("zu", "Zulu"),
)

LANGUAGE_KEYS = dict(LANGUAGES).keys()
