# coding=utf-8
""""Languages from ISO-939-1

.. note:: This program is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

"""

__author__ = 'elpaso@itopen.it'
__date__ = '2019-05-07'
__copyright__ = 'Copyright 2019, ItOpen'


LANGUAGES = (
  ("aa", "Afar"),
  ("ab", "Abkhazian"),
  ("ae", "Avestan"),
  ("af", "Afrikaans"),
  ("ak", "Akan"),
  ("am", "Amharic"),
  ("an", "Aragonese"),
  ("ar", "Arabic"),
  ("as", "Assamese"),
  ("av", "Avaric"),
  ("ay", "Aymara"),
  ("az", "Azerbaijani"),
  ("ba", "Bashkir"),
  ("be", "Belarusian"),
  ("bg", "Bulgarian"),
  ("bh", "Bihari languages"),
  ("bi", "Bislama"),
  ("bm", "Bambara"),
  ("bn", "Bengali"),
  ("bo", "Tibetan"),
  ("br", "Breton"),
  ("bs", "Bosnian"),
  ("ca", "Catalan; Valencian"),
  ("ce", "Chechen"),
  ("ch", "Chamorro"),
  ("co", "Corsican"),
  ("cr", "Cree"),
  ("cs", "Czech"),
  ("cu", "Church Slavic"),
  ("cv", "Chuvash"),
  ("cy", "Welsh"),
  ("da", "Danish"),
  ("de", "German"),
  ("dv", "Divehi; Dhivehi; Maldivian"),
  ("dz", "Dzongkha"),
  ("ee", "Ewe"),
  ("el", "Greek, Modern"),
  ("en", "English"),
  ("eo", "Esperanto"),
  ("es", "Spanish; Castilian"),
  ("et", "Estonian"),
  ("eu", "Basque"),
  ("fa", "Persian"),
  ("ff", "Fulah"),
  ("fi", "Finnish"),
  ("fj", "Fijian"),
  ("fo", "Faroese"),
  ("fr", "French"),
  ("fy", "Western Frisian"),
  ("ga", "Irish"),
  ("gd", "Gaelic; Scottish Gaelic"),
  ("gl", "Galician"),
  ("gn", "Guarani"),
  ("gu", "Gujarati"),
  ("gv", "Manx"),
  ("ha", "Hausa"),
  ("he", "Hebrew"),
  ("hi", "Hindi"),
  ("ho", "Hiri Motu"),
  ("hr", "Croatian"),
  ("ht", "Haitian; Haitian Creole"),
  ("hu", "Hungarian"),
  ("hy", "Armenian"),
  ("hz", "Herero"),
  ("ia", "Interlingua"),
  ("id", "Indonesian"),
  ("ie", "Interlingue; Occidental"),
  ("ig", "Igbo"),
  ("ii", "Sichuan Yi; Nuosu"),
  ("ik", "Inupiaq"),
  ("io", "Ido"),
  ("is", "Icelandic"),
  ("it", "Italian"),
  ("iu", "Inuktitut"),
  ("ja", "Japanese"),
  ("jv", "Javanese"),
  ("ka", "Georgian"),
  ("kg", "Kongo"),
  ("ki", "Kikuyu; Gikuyu"),
  ("kj", "Kuanyama; Kwanyama"),
  ("kk", "Kazakh"),
  ("kl", "Kalaallisut; Greenlandic"),
  ("km", "Central Khmer"),
  ("kn", "Kannada"),
  ("ko", "Korean"),
  ("kr", "Kanuri"),
  ("ks", "Kashmiri"),
  ("ku", "Kurdish"),
  ("kv", "Komi"),
  ("kw", "Cornish"),
  ("ky", "Kirghiz; Kyrgyz"),
  ("la", "Latin"),
  ("lb", "Luxembourgish; Letzeburgesch"),
  ("lg", "Ganda"),
  ("li", "Limburgan; Limburger; Limburgish"),
  ("ln", "Lingala"),
  ("lo", "Lao"),
  ("lt", "Lithuanian"),
  ("lu", "Luba-Katanga"),
)

LANGUAGE_KEYS = dict(LANGUAGES).keys()