# Generated by Django 2.2.1 on 2019-05-08 09:05

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import qgisfeed.models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QgisFeedEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('image', models.ImageField(blank=True, height_field='image_height', null=True, upload_to='feedimages', verbose_name='Image', width_field='image_width')),
                ('content', tinymce.models.HTMLField()),
                ('url', models.URLField(blank=True, help_text='URL for more information link', null=True, verbose_name='URL')),
                ('image_height', models.IntegerField(blank=True, editable=False, null=True, verbose_name='Image height')),
                ('image_width', models.IntegerField(blank=True, editable=False, null=True, verbose_name='Image width')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Creation date')),
                ('modified', models.DateField(auto_now=True, verbose_name='Modification date')),
                ('published', models.BooleanField(db_index=True, default=False, verbose_name='Published')),
                ('sticky', models.BooleanField(default=False, help_text='Check this option to keep this entry on top', verbose_name='Sticky entry')),
                ('sorting', models.PositiveIntegerField(db_index=True, default=0, help_text='Increase to show at top of the list', verbose_name='Sorting order')),
                ('language_filter', qgisfeed.models.QgisLanguageField(blank=True, choices=[('aa', 'Afar'), ('ab', 'Abkhazian'), ('ae', 'Avestan'), ('af', 'Afrikaans'), ('ak', 'Akan'), ('am', 'Amharic'), ('an', 'Aragonese'), ('ar', 'Arabic'), ('as', 'Assamese'), ('av', 'Avaric'), ('ay', 'Aymara'), ('az', 'Azerbaijani'), ('ba', 'Bashkir'), ('be', 'Belarusian'), ('bg', 'Bulgarian'), ('bh', 'Bihari languages'), ('bi', 'Bislama'), ('bm', 'Bambara'), ('bn', 'Bengali'), ('bo', 'Tibetan'), ('br', 'Breton'), ('bs', 'Bosnian'), ('ca', 'Catalan; Valencian'), ('ce', 'Chechen'), ('ch', 'Chamorro'), ('co', 'Corsican'), ('cr', 'Cree'), ('cs', 'Czech'), ('cu', 'Church Slavic'), ('cv', 'Chuvash'), ('cy', 'Welsh'), ('da', 'Danish'), ('de', 'German'), ('dv', 'Divehi; Dhivehi; Maldivian'), ('dz', 'Dzongkha'), ('ee', 'Ewe'), ('el', 'Greek, Modern'), ('en', 'English'), ('eo', 'Esperanto'), ('es', 'Spanish; Castilian'), ('et', 'Estonian'), ('eu', 'Basque'), ('fa', 'Persian'), ('ff', 'Fulah'), ('fi', 'Finnish'), ('fj', 'Fijian'), ('fo', 'Faroese'), ('fr', 'French'), ('fy', 'Western Frisian'), ('ga', 'Irish'), ('gd', 'Gaelic; Scottish Gaelic'), ('gl', 'Galician'), ('gn', 'Guarani'), ('gu', 'Gujarati'), ('gv', 'Manx'), ('ha', 'Hausa'), ('he', 'Hebrew'), ('hi', 'Hindi'), ('ho', 'Hiri Motu'), ('hr', 'Croatian'), ('ht', 'Haitian; Haitian Creole'), ('hu', 'Hungarian'), ('hy', 'Armenian'), ('hz', 'Herero'), ('ia', 'Interlingua'), ('id', 'Indonesian'), ('ie', 'Interlingue; Occidental'), ('ig', 'Igbo'), ('ii', 'Sichuan Yi; Nuosu'), ('ik', 'Inupiaq'), ('io', 'Ido'), ('is', 'Icelandic'), ('it', 'Italian'), ('iu', 'Inuktitut'), ('ja', 'Japanese'), ('jv', 'Javanese'), ('ka', 'Georgian'), ('kg', 'Kongo'), ('ki', 'Kikuyu; Gikuyu'), ('kj', 'Kuanyama; Kwanyama'), ('kk', 'Kazakh'), ('kl', 'Kalaallisut; Greenlandic'), ('km', 'Central Khmer'), ('kn', 'Kannada'), ('ko', 'Korean'), ('kr', 'Kanuri'), ('ks', 'Kashmiri'), ('ku', 'Kurdish'), ('kv', 'Komi'), ('kw', 'Cornish'), ('ky', 'Kirghiz; Kyrgyz'), ('la', 'Latin'), ('lb', 'Luxembourgish; Letzeburgesch'), ('lg', 'Ganda'), ('li', 'Limburgan; Limburger; Limburgish'), ('ln', 'Lingala'), ('lo', 'Lao'), ('lt', 'Lithuanian'), ('lu', 'Luba-Katanga')], db_index=True, help_text='The entry will be hidden to users who have not set a matching language filter', max_length=3, null=True, verbose_name='Language filter')),
                ('spatial_filter', django.contrib.gis.db.models.fields.PolygonField(blank=True, help_text='The entry will be hidden to users who have set a location that does not match', null=True, srid=4326, verbose_name='Spatial filter')),
                ('publication_start', models.DateField(blank=True, db_index=True, null=True, verbose_name='Publication start')),
                ('publication_end', models.DateField(blank=True, db_index=True, null=True, verbose_name='Publication end')),
                ('author', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'QGIS Feed Entry',
                'verbose_name_plural': 'QGIS Feed Entries',
                'db_table': '',
                'ordering': ('-sorting', '-created'),
                'managed': True,
            },
        ),
    ]
