# Generated by Django 2.2.1 on 2019-05-07 11:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qgisfeed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qgisfeedentry',
            name='author',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='qgisfeedentry',
            name='image_height',
            field=models.IntegerField(blank=True, editable=False, null=True, verbose_name='Image height'),
        ),
        migrations.AlterField(
            model_name='qgisfeedentry',
            name='image_width',
            field=models.IntegerField(blank=True, editable=False, null=True, verbose_name='Image width'),
        ),
        migrations.AlterField(
            model_name='qgisfeedentry',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
    ]
