# Generated by Django 2.2.1 on 2019-05-09 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qgisfeed', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qgisfeedentry',
            options={'managed': True, 'ordering': ('-sticky', '-sorting', '-created'), 'verbose_name': 'QGIS Feed Entry', 'verbose_name_plural': 'QGIS Feed Entries'},
        ),
        migrations.RenameField(
            model_name='qgisfeedentry',
            old_name='publication_end',
            new_name='publish_to',
        ),
        migrations.RemoveField(
            model_name='qgisfeedentry',
            name='publication_start',
        ),
        migrations.AddField(
            model_name='qgisfeedentry',
            name='publish_from',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Publication start'),
        ),
    ]
