# Generated by Django 2.2.1 on 2019-05-18 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qgisfeed', '0002_auto_20190509_1310'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qgisfeedentry',
            options={'managed': True, 'ordering': ('-sticky', '-sorting', '-publish_from'), 'verbose_name': 'QGIS Feed Entry', 'verbose_name_plural': 'QGIS Feed Entries'},
        ),
    ]
