# Generated by Django 2.2.1 on 2019-05-07 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qgisfeed', '0003_auto_20190507_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='qgisfeedentry',
            name='published',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Published'),
        ),
    ]
