# Generated by Django 2.2.1 on 2019-07-09 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qgisfeed', '0004_auto_20190709_0810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qgisfeedentry',
            name='url',
            field=models.URLField(default='http://www.qgis.org', help_text='URL for more information link', verbose_name='URL'),
            preserve_default=False,
        ),
    ]
