# Generated by Django 4.0.3 on 2022-03-26 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_visit', '0002_add_created_at'),
        ('qgisfeed', '0006_auto_20220325_0652'),
    ]

    operations = [
        migrations.CreateModel(
            name='QgisUserVisit',
            fields=[
                ('user_visit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='user_visit.uservisit')),
                ('location', models.JSONField()),
                ('qgis_version', models.CharField(blank=True, default='', max_length=255)),
                ('platform', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
    ]
