# Generated by Django 4.2.6 on 2023-10-27 12:51

from django.db import migrations
import qgisfeed.models


class Migration(migrations.Migration):

    dependencies = [
        ('qgisfeed', '0009_characterlimitconfiguration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qgisfeedentry',
            name='content',
            field=qgisfeed.models.ConfigurableCharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='qgisfeedentry',
            name='title',
            field=qgisfeed.models.ConfigurableCharField(max_length=255, verbose_name='Title'),
        ),
    ]
