# Generated by Django 4.2.6 on 2023-12-07 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qgisfeed', '0012_alter_qgisfeedentry_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qgisfeedentry',
            name='publish_to',
            field=models.DateTimeField(blank=True, db_index=True, help_text='The entry will be hidden to users after this date. You can set this in the past to temove the entry from the users listing.', null=True, verbose_name='Publication end'),
        ),
    ]
